### ISSUE TITLE
Publish to cordova registry

### ISSUE THREAD

**Issue by pavei** [andischerer/cordova-plugin-openfilenative#3]
Please!

I need to build with phonegap build!

**Comment by andischerer** [comment]
The cordova plugin is published to [npmjs registry](https://www.npmjs.com/package/cordova-plugin-openfilenative) according to the [cordova announcement](https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html).
Does it work for phonegap build if you install the plugin via `cordova plugin add cordova-plugin-openfilenative` ?
Cordova CLI 5.0.0 is necessary.

**Comment by andischerer** [comment]
[npm Plugins Are Now on PhoneGap Build!](http://phonegap.com/blog/2015/05/26/npm-plugins-available/)
