### ISSUE TITLE
shouldOverrideUrlLoading() returnsfalse issue

### ISSUE THREAD

**Issue by niyazafazl** [andischerer/cordova-plugin-openfilenative#4]
I have implemented this plugin for my Cordova (phonegap) project (cordova version 5.0.0) and the android@4.0.0.

I run this though CLI - cordova plugin add br.paveisistemas.com.cordova-plugin-openfilenative

It creates OpenFileNative .js and .java files.

And my code is as below

     $(function(){
                alert("reached");
        	$('body').on('click', 'a.openFileNative', function(e) {
        	    alert("working"+ JSON.stringify(e));
    			e.preventDefault();
             window.openFileNative.open($(this).attr('href'));
        });
       });

        In body - <a href="pdf/testfile.pdf">Open PDF on Android</a>

When I run through android phonegap build, it shows the below in my logcat and its not opened the pdf file as well.

/com.example.pdfnative D/WebCore﹕ uiOverrideUrlLoading: shouldOverrideUrlLoading() returnsfalse
/com.example.pdfnative D/JsMessageQueue﹕ Set native->JS mode to null
/com.example.pdfnative D/CordovaWebViewImpl﹕ onPageDidNavigate(file:///android_asset/www/pdf/testfile.pdf)
/com.example.pdfnative I/GATE﹕ <GATE-M>DEV_ACTION_COMPLETED</GATE-M>
/com.example.pdfnative D/CordovaWebViewImpl﹕ onPageFinished(file:///android_asset/www/pdf/testfile.pdf)

Please advice what is wrong in this? Do I want to include anything in my config.xml file.

Thanks!

**Comment by andischerer** [comment]
You are using a fork from my plugin: https://github.com/paveisistemas/cordova-plugin-openfilenative
Try to install the plugin via cli cmd: 
```
cordova plugin add cordova-plugin-openfilenative
```
