### ISSUE TITLE
Download error: file null does not exist. could not be opened.

### ISSUE THREAD

**Issue by naatogmagithub** [andischerer/cordova-plugin-openfilenative#5]
I have a pdf file named, lazy.pdf in img folder of the www folder.
I referenced it as window.openFileNative.open($(this).attr("img/lazy.pdf"));.
But I still get an error.

I tried absolute URI But it was still the same error.
Any help will be appreciated.

**Comment by andischerer** [comment]
try `window.openFileNative.open("img/lazy.pdf");`
